name: FRONT_CICD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - uses: actions/checkout@v2
      - name: build and release to DockerHub
        env:
          NAME: brinst07
        run: |
          docker build . -t brinst07/proup_front:latest
          docker push brinst07/proup_front
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy in EC2
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          command: |
            sudo docker pull brinst07/proup_front
            sudo docker-compose up -d
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
